// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBkHsx8f2MytyRIH0UVa-vP0Mr8I6WLaA',
    appId: '1:475822111600:web:184e7f9c4d82996146adb5',
    messagingSenderId: '475822111600',
    projectId: 'gp-arabic-search-engine',
    authDomain: 'gp-arabic-search-engine.firebaseapp.com',
    storageBucket: 'gp-arabic-search-engine.firebasestorage.app',
    measurementId: 'G-0C12E4JTJD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9iIuqCm-seeEyLmFbO6a4dtwu-tKrXdA',
    appId: '1:475822111600:android:5f3e226a1522ef9846adb5',
    messagingSenderId: '475822111600',
    projectId: 'gp-arabic-search-engine',
    storageBucket: 'gp-arabic-search-engine.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH08Z3RpSy2ocgQ8wq_HiY0K5SIpnZvmc',
    appId: '1:475822111600:ios:9e8a8f7843f54dd346adb5',
    messagingSenderId: '475822111600',
    projectId: 'gp-arabic-search-engine',
    storageBucket: 'gp-arabic-search-engine.firebasestorage.app',
    iosBundleId: 'com.example.signUp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBkHsx8f2MytyRIH0UVa-vP0Mr8I6WLaA',
    appId: '1:475822111600:web:d7518be01c88412046adb5',
    messagingSenderId: '475822111600',
    projectId: 'gp-arabic-search-engine',
    authDomain: 'gp-arabic-search-engine.firebaseapp.com',
    storageBucket: 'gp-arabic-search-engine.firebasestorage.app',
    measurementId: 'G-W571WNQYXG',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAH08Z3RpSy2ocgQ8wq_HiY0K5SIpnZvmc',
    appId: '1:475822111600:ios:9e8a8f7843f54dd346adb5',
    messagingSenderId: '475822111600',
    projectId: 'gp-arabic-search-engine',
    storageBucket: 'gp-arabic-search-engine.firebasestorage.app',
    iosBundleId: 'com.example.signUp',
  );

}